//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Ciribob.DCS.SimpleRadio.Standalone.Client.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("westus")]
        public string SpeechRegion {
            get {
                return ((string)(this["SpeechRegion"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("add_key")]
        public string SpeechSubscriptionKey {
            get {
                return ((string)(this["SpeechSubscriptionKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("add_custom_endpoint_id")]
        public string SpeechCustomEndpointId {
            get {
                return ((string)(this["SpeechCustomEndpointId"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("add_luis_app_id")]
        public string LuisAppId {
            get {
                return ((string)(this["LuisAppId"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("add_luis_endpoint_key")]
        public string LuisEndpointKey {
            get {
                return ((string)(this["LuisEndpointKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("localhost")]
        public string TacScribeHost {
            get {
                return ((string)(this["TacScribeHost"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5432")]
        public int TacScribePort {
            get {
                return ((int)(this["TacScribePort"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("tac_scribe")]
        public string TacScribeDatabase {
            get {
                return ((string)(this["TacScribeDatabase"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("tac_scribe")]
        public string TacScribeUsername {
            get {
                return ((string)(this["TacScribeUsername"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("tac_scribe")]
        public string TacScribePassword {
            get {
                return ((string)(this["TacScribePassword"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool TacScribeForceSSL {
            get {
                return ((bool)(this["TacScribeForceSSL"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("add_luis_endpoint_key")]
        public string ShadowLuisEndpointKey {
            get {
                return ((string)(this["ShadowLuisEndpointKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("add_luis_app_id")]
        public string ShadowLuisAppId {
            get {
                return ((string)(this["ShadowLuisAppId"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("add_discord_token")]
        public string DiscordToken {
            get {
                return ((string)(this["DiscordToken"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public ulong TransmissionLogDiscordGuild {
            get {
                return ((ulong)(this["TransmissionLogDiscordGuild"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("add_server_name_here")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("90")]
        public int WindHeading {
            get {
                return ((int)(this["WindHeading"]));
            }
        }
    }
}
